### ISSUE TITLE
Customer endpoint [GET] returns code 500

### ISSUE THREAD

**Issue by NickMns** [NickMns/screwdriver#23]
During testing of new Customer/Devices endpoints, the following issue was found.\

When calling /customers with [GET] the server returns HTTP 500.\
Log from server attached.
[customers_get_log.txt](https://github.com/NickMns/screwdriver/files/2628483/customers_get_log.txt)

**Comment by GiwrgosP** [comment]
to lathos einai sto column cust_contact_num_2, arxika sto models eixe ginei lathos kai upirxan 2 cust_contact_num
