### ISSUE TITLE
Authentication/Authorization

### ISSUE THREAD

**Issue by NickMns** [NickMns/screwdriver#5]
Use Flask-Login or JWT to enforce rules

**Comment by GiwrgosP** [comment]
Validate login input - Authenticate user and create and store login session for later use.

**Comment by NickMns** [comment]
Enforce unique username @ database level

**Comment by NickMns** [comment]
Related to #32 

- Registration & Login ready
- Roles (Not integrated into flask authorization yet)

**Comment by NickMns** [comment]
Closed.

1. DB Schema includes (Users, Roles, User-Roles Mapping)
2. API provisions for User-Role mapping/delete/update
3. Android client enables/disables operations based on logged in user's assigned role
